# Generated by Django 3.2 on 2021-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BO', 'Book'), ('DO', 'Doll'), ('AC', 'Accessories'), ('OT', 'Other')], default='ot', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'secondary'), ('d', 'danger')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
