# Generated by Django 4.0.6 on 2022-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Karussell', 'verbose_name_plural': 'Karussellen'},
        ),
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
    ]
