# Generated by Django 4.0.5 on 2022-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoryitem_options_alter_itemimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Lieferpreis'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Rabatt'),
        ),
    ]
