# Generated by Django 4.0.4 on 2022-06-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='additional_information_image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='additional_information_image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='additional_information_image3',
        ),
    ]
