# Generated by Django 4.0.4 on 2022-06-18 16:51

import core.models
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_item_additional_information_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Item video'),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delivery price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_image',
            field=models.ImageField(upload_to=core.models.item_image_path, verbose_name='Title image'),
        ),
    ]
