# Generated by Django 4.0.6 on 2022-07-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Grund')),
                ('accepted', models.BooleanField(default=False, verbose_name='Akzeptiert')),
                ('image', models.ImageField(null=True, upload_to='refund/', verbose_name='Image')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Bestellung')),
            ],
        ),
    ]
