# Generated by Django 4.0.6 on 2022-07-08 13:40

import checkout.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addressen'},
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_apartment_address',
            field=models.CharField(max_length=100, verbose_name='Abrechnung Wohnung/Firma'),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_city',
            field=models.CharField(max_length=100, verbose_name='Abrechnung Stadt'),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_country',
            field=django_countries.fields.CountryField(countries=checkout.models.EUCountries, max_length=2, verbose_name='Abrechnung Land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_name',
            field=models.CharField(max_length=120, verbose_name='Abrechnung voller Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_street_address',
            field=models.CharField(max_length=100, verbose_name='Abrechnung Strasse, Hausnummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='Speichern'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipping_apartment_address',
            field=models.CharField(max_length=100, verbose_name='Versand Wohnung/Firma'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipping_city',
            field=models.CharField(max_length=100, verbose_name='Versand Stadt'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipping_country',
            field=django_countries.fields.CountryField(countries=checkout.models.EUCountries, max_length=2, verbose_name='Versand Land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipping_name',
            field=models.CharField(max_length=120, verbose_name='Versand voller Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipping_street_address',
            field=models.CharField(max_length=100, verbose_name='Versand Strasse, Hausnummer'),
        ),
    ]
