# Generated by Django 4.0.4 on 2022-06-03 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='Bestellt')),
                ('quantity', models.IntegerField(default='1', verbose_name='Menge')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
                ('checked_out', models.BooleanField(default=False, verbose_name='Abgemeldet')),
                ('session_key', models.CharField(blank=True, max_length=60, null=True)),
                ('items', models.ManyToManyField(blank=True, to='cart.cartitem', verbose_name='Artikeln')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warenkorb',
                'verbose_name_plural': 'Warenkorben',
                'ordering': ('-creation_date',),
                'unique_together': {('user', 'session_key')},
            },
        ),
    ]
