# Generated by Django 4.0.4 on 2022-06-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_cart'),
        ('cart', '0002_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order'),
        ),
    ]
