# Generated by Django 4.0.4 on 2022-06-21 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name_for_delivery', models.CharField(max_length=120, verbose_name='Vollständiger Name')),
                ('street_address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('apartment_address', models.CharField(max_length=100, verbose_name='Apartment address')),
                ('country', django_countries.fields.CountryField(countries=order.models.EUCountries, max_length=2, verbose_name='Land')),
                ('zip', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('B', 'Abrechnung'), ('S', 'Versand')], max_length=1, verbose_name='Adresstyp')),
                ('default', models.BooleanField(default=False, verbose_name='Standard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
                ('ordered', models.BooleanField(default=False, verbose_name='Bestellt')),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='Bestelldatum')),
                ('ref_code', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Referenzcode')),
                ('being_delivered', models.BooleanField(default=False, verbose_name='Wird geliefert')),
                ('tracking_number', models.CharField(blank=True, max_length=240, null=True, verbose_name='Sendungscode')),
                ('refund_requested', models.BooleanField(default=False, verbose_name='Rückerstattung beantragt')),
                ('refund_granted', models.BooleanField(default=False, verbose_name='Rückerstattung gewährt')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='order.address', verbose_name='Rechnungsadresse')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='order.address', verbose_name='Lieferadresse')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellung',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='TrackingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tracking_link', models.CharField(max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'Tracking-Unternehmen',
                'verbose_name_plural': 'Tracking-Unternehmen',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Grund')),
                ('accepted', models.BooleanField(default=False, verbose_name='Akzeptiert')),
                ('image', models.ImageField(null=True, upload_to='refund/', verbose_name='Image')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Bestellung')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='1', verbose_name='Menge')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='Artikel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Bestellung')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.trackingcompany', verbose_name='Tracking-Unternehmen'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'session_key')},
        ),
    ]
