# Generated by Django 4.0.6 on 2022-07-07 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
                ('ordered', models.BooleanField(default=False, verbose_name='Bestellt')),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='Bestelldatum')),
                ('ref_code', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Referenzcode')),
                ('being_delivered', models.BooleanField(default=False, verbose_name='Wird geliefert')),
                ('tracking_number', models.CharField(blank=True, max_length=240, null=True, verbose_name='Sendungscode')),
                ('refund_requested', models.BooleanField(default=False, verbose_name='Refund angefordert')),
                ('refund_granted', models.BooleanField(default=False, verbose_name='Refundgewährt')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='checkout.address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='TrackingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tracking_link', models.CharField(max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'Tracking company',
                'verbose_name_plural': 'Tracking companies',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='1', verbose_name='Menge')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='Artikel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Bestellung')),
            ],
            options={
                'verbose_name': 'Warenkorb Artikel',
                'verbose_name_plural': 'Warenkorb Artikeln',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.trackingcompany', verbose_name='Tracking company'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'session_key')},
        ),
    ]
