# Generated by Django 4.0.5 on 2022-07-03 09:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name_for_delivery',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='address',
            name='billing_apartment_address',
            field=models.CharField(default='default', max_length=100, verbose_name='Billing apartment address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='billing_city',
            field=models.CharField(default='default city', max_length=100, verbose_name='Billing city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='billing_country',
            field=django_countries.fields.CountryField(countries=order.models.EUCountries, default='DE', max_length=2, verbose_name='Billing country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='billing_name',
            field=models.CharField(default='Name', max_length=120, verbose_name='Billing full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='billing_street_address',
            field=models.CharField(default='address', max_length=100, verbose_name='Billing street address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='billing_zip',
            field=models.CharField(default='012345', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_apartment_address',
            field=models.CharField(default='apartment', max_length=100, verbose_name='Shipping apartment address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_city',
            field=models.CharField(default='city', max_length=100, verbose_name='Shipping city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_country',
            field=django_countries.fields.CountryField(countries=order.models.EUCountries, default='DE', max_length=2, verbose_name='Shipping country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_name',
            field=models.CharField(default='name', max_length=120, verbose_name='Shipping full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_street_address',
            field=models.CharField(default='street', max_length=100, verbose_name='Shipping street address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='shipping_zip',
            field=models.CharField(default='01234', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='order.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Save for future usage'),
        ),
    ]
