# Generated by Django 4.0.4 on 2022-06-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options'),
        ('order', '0003_alter_refund_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart', verbose_name='Warenkorb'),
        ),
    ]
