# Generated by Django 4.0.4 on 2022-06-20 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Bestellung'),
        ),
    ]
