# Generated by Django 4.0.4 on 2022-06-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_refund_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
