# Generated by Django 4.0.4 on 2022-06-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_order'),
        ('order', '0008_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
        migrations.AddField(
            model_name='refund',
            name='image',
            field=models.ImageField(null=True, upload_to='refund/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Warenkorb'),
        ),
    ]
